# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentRunner < Formula
  desc "CLI workflow orchestrator for AI agents"
  homepage "https://github.com/Codagent-AI/agent-runner"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v0.2.0/agent-runner_darwin_amd64.tar.gz"
      sha256 "847cc324545269a5d4174ab269391a1cf935ead72b5f80fbe858270f7f0de9e3"

      define_method(:install) do
        bin.install "agent-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v0.2.0/agent-runner_darwin_arm64.tar.gz"
      sha256 "0ee9534deca433b91bbf3dd4ec87003a01d9d133a10d03f91514b1a9e07089bd"

      define_method(:install) do
        bin.install "agent-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v0.2.0/agent-runner_linux_amd64.tar.gz"
      sha256 "2f997d282a12afeb01c9b515f4d5b335592ea666ddc9575b5123d56d575dcf65"
      define_method(:install) do
        bin.install "agent-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v0.2.0/agent-runner_linux_arm64.tar.gz"
      sha256 "85660b89fafcb54d525d288405d3103047bf5bc1b1d1be24bd2bb2670abc1323"
      define_method(:install) do
        bin.install "agent-runner"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-runner --version")
  end
end
