# typed: false
# frozen_string_literal: true

# This file was generated by the agent-validator release workflow. DO NOT EDIT.
class AgentValidator < Formula
  desc "CLI tool for validating AI coding agents"
  homepage "https://github.com/Codagent-AI/agent-validator"
  url "https://registry.npmjs.org/agent-validator/-/agent-validator-1.15.0.tgz"
  sha256 "874c2a28aa4bb14769cad6c9c6571e10599085752c3a65d9f4cff42208b38c47"
  version "1.15.0"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    shell_output("#{bin}/agent-validate --version")
    shell_output("#{bin}/agent-validator --version")
  end
end
