# typed: false
# frozen_string_literal: true

# This file was generated by the agent-validator release workflow. DO NOT EDIT.
class AgentValidator < Formula
  desc "CLI tool for validating AI coding agents"
  homepage "https://github.com/Codagent-AI/agent-validator"
  url "https://registry.npmjs.org/agent-validator/-/agent-validator-1.11.4.tgz"
  sha256 "644a9a715c5aef5362fd109391de20985b7f0116e5369c0212043c241c244f2d"
  version "1.11.4"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    shell_output("#{bin}/agent-validate --version")
    shell_output("#{bin}/agent-validator --version")
  end
end
