# typed: false
# frozen_string_literal: true

# This file was generated by the agent-validator release workflow. DO NOT EDIT.
class AgentValidator < Formula
  desc "CLI tool for validating AI coding agents"
  homepage "https://github.com/Codagent-AI/agent-validator"
  url "https://registry.npmjs.org/agent-validator/-/agent-validator-1.13.0.tgz"
  sha256 "5f8892eaf5d37c270bcb6644aee2205b20dd6f94518b60671e3bb4e415d71249"
  version "1.13.0"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    shell_output("#{bin}/agent-validate --version")
    shell_output("#{bin}/agent-validator --version")
  end
end
