# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-runner" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "352c00f3218ad9616657196e2349920a175a901600424f6d9b2d7feeadc7e5f9"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d109e48f59b410ff7b560e44423502704180e8bf4636660ca1406b5b16e1e830"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "712f143f375734e8885cbd128cbf83dc804d3d671260dcdcc8a9b3b4e8b88dbb"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7df119395554e1e0bff1d318d6ebbef0cb941e7f2c598f16ce454566cd28e53"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_linux_arm64.tar.gz"
    end
  end

  name "agent-runner"
  desc "CLI workflow orchestrator for AI agents"
  homepage "https://github.com/Codagent-AI/agent-runner"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "agent-validator",
    ]

  binary "agent-runner"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-runner"]
    end
  end

  # No zap stanza required

end
