# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-runner" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "d1b2c0523680cc6ab1a79810d477907f24414172aa51440b506ba21113bd78d7"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3b5a32fba5f7f8cbcfbcee57b6f2d93b49d6ac2e3bc3fc7e26e4c306557ab35"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "14a23eb47ad7788789cfe79408fd5ef741bec255c708cae523fc24664ac007fe"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "562bbbde214985ece235bd2ab374c63edfce5137d9e2aca26901c652563a7d76"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_linux_arm64.tar.gz"
    end
  end

  name "agent-runner"
  desc "CLI workflow orchestrator for AI agents"
  homepage "https://github.com/Codagent-AI/agent-runner"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "agent-plugin",
      "agent-validator",
    ]

  binary "agent-runner"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-runner"]
    end
  end

  # No zap stanza required

end
