# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-runner" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "70b1ff5fe4dd7ae11eac5c646d7ece5de93320a277e45167f058e27daf86e53f"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7720cb8eb9f450759096c4c07ca244f7a167aac74391d38635fab92c6559a98"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f61e0106b24c0e79ab9507f58503b4c0ffa988be5908e23cf74f299ea3cc47a1"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb15b8a9cae69d90bd3c50a50783ce60a3e8cc58ba33c6036a97916fdb06301f"
      url "https://github.com/Codagent-AI/agent-runner/releases/download/v#{version}/agent-runner_linux_arm64.tar.gz"
    end
  end

  name "agent-runner"
  desc "CLI workflow orchestrator for AI agents"
  homepage "https://github.com/Codagent-AI/agent-runner"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "agent-validator",
    ]

  binary "agent-runner"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-runner"]
    end
  end

  # No zap stanza required

end
